name: git-to-prod
on:
  push:
    branches:
      - main
env:
  MB_VERSION: 1.46.4
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_HOST: ${{ secrets.MB_DB_HOST }}
  MB_DB_USER: ${{ secrets.MB_DB_USER }}
  MB_DB_PASS: ${{ secrets.MB_DB_PASS }}

jobs:
  import-curated-collections:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download selected version enterprise jar
        run: |
          curl -OL https://downloads.metabase.com/enterprise/v$MB_VERSION/metabase.jar
          stat ./metabase.jar
      - name: Import to production
        run: |
          java -jar metabase.jar import $GITHUB_WORKSPACE
